services:
    db:
        image: postgres
        container_name: local_pgdb
        restart: always
        env_file: ./.env
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${PG_DB_USER}
            POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
            POSTGRES_DB: ${PG_DB_DATABASE}
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        env_file: ./.env
        ports:
            - '8080:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PG_DB_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PG_DB_PASSWORD}
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    local_pgdata:
    pgadmin-data:
